<a href="https://colab.research.google.com/github/Neulvo/TIL/blob/master/07_Practice_Document_Representation%E1%84%8B%E1%85%B4_tfidf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 7장. 문장의 표현 (Sentence Representation)

# 1 BoW (Bag of Words)

<img src="https://image.slidesharecdn.com/vector-space-models-170118145044/95/cs571-vector-space-models-3-638.jpg?cb=1485433004" />

https://en.wikipedia.org/wiki/Bag-of-words_model
https://www.slideshare.net/jchoi7s/cs571-vector-space-models

## 1.1 직접구현

In [1]:
import pandas as pd

In [2]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

### 1) 띄어쓰기 단위로 토큰화

In [3]:
doc_ls = [doc.split() for doc in docs]
doc_ls

[['오늘', '동물원에서', '원숭이를', '봤어'],
 ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

### 2) 각 고유 토큰에 인덱스(Index)를 지정

In [4]:
from collections import defaultdict
word2id= defaultdict(lambda : len(word2id))
[word2id[token] for doc in doc_ls for token in doc]
word2id

defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '바나나를': 6,
             '봤어': 3,
             '오늘': 0,
             '원숭이를': 2,
             '원숭이에게': 5,
             '줬어': 7,
             '코끼리를': 4})

### 3) BoW 생성

In [6]:
import numpy as np
Bow_ls =[]

for i, doc in enumerate(doc_ls):
  bow = np.zeros(len(word2id), dtype=int)
  for token in doc:
    bow[word2id[token]] +=1
  Bow_ls.append(bow.tolist())
Bow_ls

[[1, 1, 1, 1, 0, 0, 0, 0], [1, 1, 0, 2, 1, 0, 0, 0], [0, 1, 0, 0, 0, 1, 2, 1]]

In [9]:
from IPython.core import display as ICD
sorted_vocab = sorted((value,key) for key, value in word2id.items())
vocab=[v[1] for v in sorted_vocab]

for i in range(len(docs)):
  print("문서{} : {}".format(i, docs[i]))
  ICD.display(pd.DataFrame([Bow_ls[i]],columns=vocab))
  print('\n\n')

문서0 : 오늘 동물원에서 원숭이를 봤어


오늘  동물원에서  원숭이를  봤어  코끼리를  원숭이에게  바나나를  줬어
0   1      1     1   1     0      0     0   0




문서1 : 오늘 동물원에서 코끼리를 봤어 봤어


오늘  동물원에서  원숭이를  봤어  코끼리를  원숭이에게  바나나를  줬어
0   1      1     0   2     1      0     0   0




문서2 : 동물원에서 원숭이에게 바나나를 줬어 바나나를


오늘  동물원에서  원숭이를  봤어  코끼리를  원숭이에게  바나나를  줬어
0   0      1     0   0     0      1     2   1

## 1.2 단어 순서를 고려하지 않은 BoW

In [10]:
docs = ['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해',
        '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']

### 1) 띄어쓰기 단위로 토큰화

In [11]:
doc_ls = [doc.split() for doc in docs]
doc_ls

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

### 2) 각 고유 토큰에 인덱스(Index)를 지정

In [12]:
from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))
[word2id[token] for doc in doc_ls for token in doc]
word2id

defaultdict(<function __main__.<lambda>>,
            {'나는': 0,
             '싫어해': 6,
             '양념': 1,
             '좋아해': 3,
             '치킨을': 2,
             '하지만': 4,
             '후라이드': 5})

### 3) BoW 생성

In [13]:
import numpy as np

BoW_ls = []

for i, doc in enumerate(doc_ls):
  bow= np.zeros(len(word2id), dtype=int)
  for token in doc:
    bow[word2id[token]] +=1
  BoW_ls.append(bow.tolist())
BoW_ls

[[1, 1, 2, 1, 1, 1, 1], [1, 1, 2, 1, 1, 1, 1]]

In [15]:
from IPython.core import display as ICD

sorted_vocab = sorted((value, key) for key, value in word2id.items())
vocab=[v[1] for v in sorted_vocab]
for i in range(len(docs)):
  print('문서 {} : {}'.format(i, docs[i]))
  ICD.display(pd.DataFrame([BoW_ls[i]],columns=vocab))
  print('\n\n')

문서 0 : 나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1




문서 1 : 나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1

https://en.wikipedia.org/wiki/Document-term_matrix

## 1.3 sklearn 활용

In [16]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer()
BoW = count_vect.fit_transform(docs)

BoW.toarray()[0]

array([1, 0, 1, 1, 1, 0, 0, 0])

In [18]:
from IPython.core import display as ICD

vocab= count_vect.get_feature_names()
for i in range(len(docs)):
  print("문서 {} : {}".format(i, docs[i]))
  ICD.display(pd.DataFrame([BoW.toarray()[i]],columns=vocab))
  print('\n\n')

문서 0 : 오늘 동물원에서 원숭이를 봤어


동물원에서  바나나를  봤어  오늘  원숭이를  원숭이에게  줬어  코끼리를
0      1     0   1   1     1      0   0     0




문서 1 : 오늘 동물원에서 코끼리를 봤어 봤어


동물원에서  바나나를  봤어  오늘  원숭이를  원숭이에게  줬어  코끼리를
0      1     0   2   1     0      0   0     1




문서 2 : 동물원에서 원숭이에게 바나나를 줬어 바나나를


동물원에서  바나나를  봤어  오늘  원숭이를  원숭이에게  줬어  코끼리를
0      1     2   0   0     0      1   1     0



---


## 1.4 gensim 활용

In [19]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [20]:
import gensim
import numpy as np
from gensim import corpora

doc_ls = [doc.split() for doc in docs]
id2word = corpora.Dictionary(doc_ls)
BoW = [id2word.doc2bow(doc) for doc in doc_ls]
BoW[0]

[(0, 1), (1, 1), (2, 1), (3, 1)]

In [21]:
from gensim.matutils import sparse2full
from IPython.core import display as ICD

vocab=[id2word[i] for i in id2word.keys()]
for i in range(len(docs)):
  print('문서 {} : {}'.format(i, docs[i]))
  ICD.display(pd.DataFrame([sparse2full(BoW[i], len(vocab))],columns=vocab))
  print('\n\n')

문서 0 : 오늘 동물원에서 원숭이를 봤어


동물원에서   봤어   오늘  원숭이를  코끼리를  바나나를  원숭이에게   줬어
0    1.0  1.0  1.0   1.0   0.0   0.0    0.0  0.0




문서 1 : 오늘 동물원에서 코끼리를 봤어 봤어


동물원에서   봤어   오늘  원숭이를  코끼리를  바나나를  원숭이에게   줬어
0    1.0  2.0  1.0   0.0   1.0   0.0    0.0  0.0




문서 2 : 동물원에서 원숭이에게 바나나를 줬어 바나나를


동물원에서   봤어   오늘  원숭이를  코끼리를  바나나를  원숭이에게   줬어
0    1.0  0.0  0.0   0.0   0.0   2.0    1.0  1.0



---



# 2 TDM(Term-Document Matrix)

## 2.1 직접구현

In [22]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

### 1) 띄어쓰기 단위로 토큰화

In [23]:
doc_ls = [doc.split() for doc in docs]
doc_ls

[['오늘', '동물원에서', '원숭이를', '봤어'],
 ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

### 2) 각 고유 토큰에 인덱스(Index)를 지정

In [24]:
from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))
[word2id[token] for doc in doc_ls for token in doc ]
word2id        

defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '바나나를': 6,
             '봤어': 3,
             '오늘': 0,
             '원숭이를': 2,
             '원숭이에게': 5,
             '줬어': 7,
             '코끼리를': 4})

### 3) TDM 생성

In [25]:
import numpy as np

TDM = np.zeros((len(word2id), len(doc_ls)), dtype=int)
for i, doc in enumerate(doc_ls):
  for token in doc:
    TDM[word2id[token],i]+=1
TDM

array([[1, 1, 0],
       [1, 1, 1],
       [1, 0, 0],
       [1, 2, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 2],
       [0, 0, 1]])

In [27]:
import pandas as pd 

doc_names = ['문서'+ str(i) for i in range(len(doc_ls))]
sorted_vocab = sorted((value, key) for key, value in word2id.items())
vocab=[v[1] for v in sorted_vocab]
df_TDM = pd.DataFrame(TDM, columns=doc_names)
df_TDM['단어']=vocab 
df_TDM.set_index('단어')

문서0  문서1  문서2
단어                  
오늘       1    1    0
동물원에서    1    1    1
원숭이를     1    0    0
봤어       1    2    0
코끼리를     0    1    0
원숭이에게    0    0    1
바나나를     0    0    2
줬어       0    0    1

## 2.2 sklearn 활용

In [28]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [29]:
from sklearn.feature_extraction.text import CountVectorizer

count_vect = CountVectorizer()
DTM = count_vect.fit_transform(docs)
DTM.toarray()

array([[1, 0, 1, 1, 1, 0, 0, 0],
       [1, 0, 2, 1, 0, 0, 0, 1],
       [1, 2, 0, 0, 0, 1, 1, 0]])

In [30]:
import pandas as pd 
doc_names = ['문서'+str(i) for i in range(len(doc_ls))]
vocab= count_vect.get_feature_names()
df_TDM=pd.DataFrame(DTM.toarray().T,columns=doc_names)
df_TDM['단어']=vocab
df_TDM.set_index('단어')

문서0  문서1  문서2
단어                  
동물원에서    1    1    1
바나나를     0    0    2
봤어       1    2    0
오늘       1    1    0
원숭이를     1    0    0
원숭이에게    0    0    1
줬어       0    0    1
코끼리를     0    1    0



---


## 2.3 gensim 활용

In [31]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [33]:
import gensim
from gensim import corpora

doc_ls=[doc.split() for doc in docs]
id2word=corpora.Dictionary(doc_ls)
TDM=[id2word.doc2bow(doc) for doc in doc_ls]
TDM

[[(0, 1), (1, 1), (2, 1), (3, 1)],
 [(0, 1), (1, 2), (2, 1), (4, 1)],
 [(0, 1), (5, 2), (6, 1), (7, 1)]]

In [34]:
import pandas as pd 

doc_names = ['문서' + str(i) for i in range(len(doc_ls))]
vocab=[id2word[i] for i in id2word.keys()]
DTM_matrix = [sparse2full(doc, len(vocab)).tolist() for doc in TDM]

df_TDM = pd.DataFrame(np.array(DTM_matrix, dtype=int).T, columns=doc_names)
df_TDM['단어']=vocab
df_TDM.set_index('단어')

문서0  문서1  문서2
단어                  
동물원에서    1    1    1
봤어       1    2    0
오늘       1    1    0
원숭이를     1    0    0
코끼리를     0    1    0
바나나를     0    0    2
원숭이에게    0    0    1
줬어       0    0    1

---

# 3 TF-IDF (Term Frequency-Inverse Document Frequency)

<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/10109d0e60cc9d50a1ea2f189bac0ac29a030a00" />



*  TF(단어 빈도, Term Frequency) : 단어가 문서 내에 등장하는 빈도
*  IDF(역문서 빈도, Inverse Document Frequency) : 단어가 여러 문서에 공통적으로 등장하는 빈도
*  한 문서 내에 자주 등장하고 다른 문서에 자주 등장하지 않는 단어를 주요 단어로 판별할 수 있음


https://en.wikipedia.org/wiki/Tf%E2%80%93idf

## 3.1 직접계산하기 1

weighting schema|weight
--|--
tf (term frequency)|<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/91699003abf4fe8bdf861bbce08e73e71acf5fd4" />
idf(inverse document frequency) |<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/864fcfdc0c16344c11509f724f1aa7081cf9f657" />

In [36]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

### 1) 띄어쓰기 단위로 토큰화

In [37]:
doc_ls = [doc.split() for doc in docs]
doc_ls

[['오늘', '동물원에서', '원숭이를', '봤어'],
 ['오늘', '동물원에서', '코끼리를', '봤어', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

### 2) 각 고유 토큰에 인덱스(Index)를 지정

In [38]:
from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))
[word2id[token] for doc in doc_ls for token in doc]
word2id

defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '바나나를': 6,
             '봤어': 3,
             '오늘': 0,
             '원숭이를': 2,
             '원숭이에게': 5,
             '줬어': 7,
             '코끼리를': 4})

### 3) DTM 생성

In [40]:
import numpy as np 

DTM = np.zeros((len(doc_ls), len(word2id)), dtype=int)
for i, doc in enumerate(doc_ls):
  for token in doc:
    DTM[i, word2id[token]]+=1

DTM

array([[1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 2, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 2, 1]])

### 4) TF 계산

<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/91699003abf4fe8bdf861bbce08e73e71acf5fd4" />

TF = 문서내 토크빈도/ 문서내 전체토큰갯수

In [42]:
def computeTF(DTM):
  doc_len = len(DTM)
  word_len = len(DTM[0])

  tf = np.zeros((doc_len, word_len))

  for doc_i in range(doc_len):
    for word_i in range(word_len):
      tf[doc_i, word_i]=DTM[doc_i, word_i]/DTM[doc_i].sum()
  return tf

tf= computeTF(DTM)
tf

array([[0.25, 0.25, 0.25, 0.25, 0.  , 0.  , 0.  , 0.  ],
       [0.2 , 0.2 , 0.  , 0.4 , 0.2 , 0.  , 0.  , 0.  ],
       [0.  , 0.2 , 0.  , 0.  , 0.  , 0.2 , 0.4 , 0.2 ]])

### 5) IDF  계산

<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/864fcfdc0c16344c11509f724f1aa7081cf9f657" />

IDF = log(총문서수/토큰이등장한문서수)

In [45]:
import math

def computeIDF(DTM):
  doc_len = len(DTM)
  word_len = len(DTM[0])

  idf=np.zeros(word_len)
  for i in range(word_len):
    idf[i] = -math.log10(np.count_nonzero(DTM[:,i])/doc_len)

  return idf

computeIDF(DTM)

array([ 0.17609126, -0.        ,  0.47712125,  0.17609126,  0.47712125,
        0.47712125,  0.47712125,  0.47712125])

### 6) TF-IDF 계산

In [46]:
def computeTFIDF(DTM):
  tf = computeTF(DTM)
  idf = computeIDF(DTM)

  tfidf = np.zeros(tf.shape)
  for doc_i in range(tf.shape[0]):
    for word_i in range(tf.shape[1]):
      tfidf[doc_i, word_i] = tf[doc_i, word_i] * idf[word_i]

  return tfidf

computeTFIDF(DTM)

array([[ 0.04402281, -0.        ,  0.11928031,  0.04402281,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.03521825, -0.        ,  0.        ,  0.0704365 ,  0.09542425,
         0.        ,  0.        ,  0.        ],
       [ 0.        , -0.        ,  0.        ,  0.        ,  0.        ,
         0.09542425,  0.1908485 ,  0.09542425]])

In [47]:
import pandas as pd 

sorted_vocab = sorted((value, key) for key, value in word2id.items())
tfidf=computeTFIDF(DTM)
pd.DataFrame(tfidf, columns=vocab)

동물원에서   봤어       오늘      원숭이를      코끼리를      바나나를     원숭이에게        줬어
0  0.044023 -0.0  0.11928  0.044023  0.000000  0.000000  0.000000  0.000000
1  0.035218 -0.0  0.00000  0.070437  0.095424  0.000000  0.000000  0.000000
2  0.000000 -0.0  0.00000  0.000000  0.000000  0.095424  0.190849  0.095424

## 3.2 직접계산하기2

weighting schema|weight|설명
--|--|--
tf(double normalization 0.5)|<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/45badc1c70ec2caa00ed8c21ed75bd9f8d3e650c" />|=0.5 + 0.5(토큰빈도/문서내최빈토큰)
idf(inverse document frequency smooth)|<img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/25f4d6690acaaef1f15f308d24f6f8a439de971d" />|=log(문서갯수/(1+토큰빈도)) + 1

In [48]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [53]:
from math import log10
import numpy as np 
from collections import defaultdict

def f(t,d):
  return d.count(t)

def tf(t,d):
  return 0.5+0.5*f(t,d)/max([f(w,d) for w in d])

def idf(t,D):
  num = len(D)
  den = 1 + len([True for d in D if t in d])
  return 1+log10(num/den)

def tfidf_score(t, d, D):
  return tf(t,d) * idf(t,D)

def tokenizer(d):
  return d.split()

def tfidfScorer(D):
  D_ls = [tokenizer(d) for d in D]
  vocab = list(set().union(*D_ls))
  word2id = defaultdict(lambda : len(word2id))
  [word2id[v] for v in vocab]

  print(word2id)

  tfidf= np.zeros((len(D_ls), len(vocab)))
  for i in range(len(D_ls)):
    for t in D_ls[i]:
      tfidf[i, word2id[t]]=tfidf_score(t, D_ls[i], D)
    
  return tfidf, vocab

tfidfScorer(docs)

defaultdict(<function tfidfScorer.<locals>.<lambda> at 0x7f4fecaaef28>, {'바나나를': 0, '원숭이를': 1, '코끼리를': 2, '봤어': 3, '오늘': 4, '원숭이에게': 5, '동물원에서': 6, '줬어': 7})


(array([[0.        , 1.17609126, 0.        , 1.        , 1.        ,
         0.        , 0.87506126, 0.        ],
        [0.        , 0.        , 0.88206844, 1.        , 0.75      ,
         0.        , 0.65629595, 0.        ],
        [1.17609126, 0.        , 0.        , 0.        , 0.        ,
         0.88206844, 0.65629595, 0.88206844]]),
 ['바나나를', '원숭이를', '코끼리를', '봤어', '오늘', '원숭이에게', '동물원에서', '줬어'])

In [54]:
print('a')
print('a', 'b')

def my_func(a, b, c, d):
  print(a, b, c, d)
my_list = ['nlp', 'image', 'voice', 'auto']
my_func(*my_list)


a
a b
nlp image voice auto


In [55]:
import pandas as pd 
tfidf, vocab = tfidfScorer(docs)
pd.DataFrame(tfidf, columns=vocab)

defaultdict(<function tfidfScorer.<locals>.<lambda> at 0x7f4fecaa01e0>, {'바나나를': 0, '원숭이를': 1, '코끼리를': 2, '봤어': 3, '오늘': 4, '원숭이에게': 5, '동물원에서': 6, '줬어': 7})


바나나를      원숭이를      코끼리를   봤어    오늘     원숭이에게     동물원에서        줬어
0  0.000000  1.176091  0.000000  1.0  1.00  0.000000  0.875061  0.000000
1  0.000000  0.000000  0.882068  1.0  0.75  0.000000  0.656296  0.000000
2  1.176091  0.000000  0.000000  0.0  0.00  0.882068  0.656296  0.882068

In [ ]:
docs = ['오늘 동물원에서 원숭이를 봤어',
        '오늘 동물원에서 코끼리를 봤어 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [56]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vect = TfidfVectorizer()
tfidf = tfidf_vect.fit_transform(docs)
print(tfidf_vect.get_feature_names())
tfidf.todense()

['동물원에서', '바나나를', '봤어', '오늘', '원숭이를', '원숭이에게', '줬어', '코끼리를']


matrix([[0.37311881, 0.        , 0.4804584 , 0.4804584 , 0.63174505,
         0.        , 0.        , 0.        ],
        [0.28680065, 0.        , 0.73861611, 0.36930805, 0.        ,
         0.        , 0.        , 0.48559571],
        [0.2344005 , 0.79374908, 0.        , 0.        , 0.        ,
         0.39687454, 0.39687454, 0.        ]])

In [57]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

count_vect = CountVectorizer()
BoW = count_vect.fit_transform(docs)
tfidf_trans = TfidfTransformer()
tfidf=tfidf_trans.fit_transform(BoW)
print(tfidf)
tfidf.todense()

  (0, 4)	0.6317450542765208
  (0, 3)	0.4804583972923858
  (0, 2)	0.4804583972923858
  (0, 0)	0.3731188059313277
  (1, 7)	0.48559571020624154
  (1, 3)	0.3693080540613576
  (1, 2)	0.7386161081227152
  (1, 0)	0.2868006489817671
  (2, 6)	0.3968745408286403
  (2, 5)	0.3968745408286403
  (2, 1)	0.7937490816572806
  (2, 0)	0.23440049712476196


matrix([[0.37311881, 0.        , 0.4804584 , 0.4804584 , 0.63174505,
         0.        , 0.        , 0.        ],
        [0.28680065, 0.        , 0.73861611, 0.36930805, 0.        ,
         0.        , 0.        , 0.48559571],
        [0.2344005 , 0.79374908, 0.        , 0.        , 0.        ,
         0.39687454, 0.39687454, 0.        ]])

In [59]:
count_vect.get_feature_names()

['동물원에서', '바나나를', '봤어', '오늘', '원숭이를', '원숭이에게', '줬어', '코끼리를']

In [60]:
import pandas as pd

vocab= count_vect.get_feature_names()
pd.DataFrame(tfidf.todense(), columns=vocab)

동물원에서      바나나를        봤어  ...     원숭이에게        줬어      코끼리를
0  0.373119  0.000000  0.480458  ...  0.000000  0.000000  0.000000
1  0.286801  0.000000  0.738616  ...  0.000000  0.000000  0.485596
2  0.234400  0.793749  0.000000  ...  0.396875  0.396875  0.000000

[3 rows x 8 columns]

In [61]:
import gensim
from gensim import corpora
from gensim.models import TfidfModel 

doc_ls = [doc.split() for doc in docs]
id2word = corpora.Dictionary(doc_ls)
TDM = [id2word.doc2bow(doc) for doc in doc_ls]
model=TfidfModel(TDM)
tfidf=model[TDM]
tfidf[0]

[(1, 0.32718457421365993), (2, 0.32718457421365993), (3, 0.8865102981879297)]

In [62]:
from gensim.matutils import sparse2full

vocab= [id2word[i] for i in id2word.keys()]
TDM_matrix = [sparse2full(doc, len(vocab)) for doc in tfidf]
pd.DataFrame(TDM_matrix, columns=vocab)

동물원에서        봤어        오늘     원숭이를      코끼리를      바나나를     원숭이에게        줬어
0    0.0  0.327185  0.327185  0.88651  0.000000  0.000000  0.000000  0.000000
1    0.0  0.569307  0.284654  0.00000  0.771272  0.000000  0.000000  0.000000
2    0.0  0.000000  0.000000  0.00000  0.000000  0.816497  0.408248  0.408248